image: docker:24.0.5  # Use a Docker image with preinstalled Docker

options:
  docker: true  # Enable Docker-in-Docker

image: maven:3.8.5-openjdk-17

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - maven
        script:
          - mvn clean package
    - step:
        name: Build and Push Docker Image
        script:
          - docker build -t vectorzy/demo-app:latest .
          - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          - docker push vectorzy/demo-app:latest
    # - step:
    #     name: Deploy to Kubernetes via ArgoCD
    #     script:
    #       - apk add --no-cache curl
    #       - curl -X POST -H "Content-Type: application/json" \
    #         -d '{"syncPolicy":{"automated":{}}}' \
    #         http://argocd-server/api/v1/applications/demo-app/sync

