image: docker:24.0.5  # Use a Docker image with preinstalled Docker

options:
  docker: true  # Enable Docker-in-Docker

image: maven:3.8.5-openjdk-17

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - maven
        script:
          - mvn clean package

    - step:
        name: Build and Push Docker Image
        script:
          - docker build -t vectorzy/demo-app:latest .
          - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          - docker push vectorzy/demo-app:latest

    - step:
        name: Security Scan
        image: aquasec/trivy  # Trivy security scanner
        script:
          - trivy --version  # Verify Trivy is installed
          - trivy image vectorzy/demo-app:latest  # Scan the Docker image for vulnerabilities
          - trivy fs .  # Optional: Scan the project dependencies for vulnerabilities

