replicaCount: 1

image:
  repository: vectorzy/demo-app  # Your Docker image repository
  tag: v3
  pullPolicy: IfNotPresent

service:
  type: NodePort # Switch between clusterIp NodePort & LoadBalancer
  port: 8080  # Port your app listens on

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

